title: West-Midwest Customer Events
description: Bookmark this page to stay up to date on all West-Midwest customer events.
# Added baseurl for assets
baseurl: "/docs"
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme